// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/cgen/certificate.dart';
import 'third_party/cgen/objects/certified_key.dart';
import 'third_party/cgen/objects/crl_distribution_point.dart';
import 'third_party/cgen/objects/custom_extension.dart';
import 'third_party/cgen/objects/date.dart';
import 'third_party/cgen/objects/dn_type.dart';
import 'third_party/cgen/objects/extended_key_usage_purpose.dart';
import 'third_party/cgen/objects/key_id_method.dart';
import 'third_party/cgen/objects/key_usage_purpose.dart';
import 'third_party/cgen/objects/rsa_key_size.dart';
import 'third_party/cgen/objects/serial_number.dart';
import 'third_party/cgen/objects/signature_algorithm.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 707498801;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rdart',
        ioDirectory: 'rust/rdart/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String cgenObjectsCertifiedKeyCertifiedKeyCertPem({
    required CertifiedKey that,
  });

  String cgenObjectsCertifiedKeyCertifiedKeySigningKeyPem({
    required CertifiedKey that,
  });

  void cgenObjectsCustomExtensionCustomExtensionContent({
    required CustomExtension that,
  });

  bool cgenObjectsCustomExtensionCustomExtensionCriticality({
    required CustomExtension that,
  });

  CustomExtension cgenObjectsCustomExtensionCustomExtensionFromOidContent({
    required Uint64List oid,
    required List<int> content,
  });

  CustomExtension? cgenObjectsCustomExtensionCustomExtensionNewAcmeIdentifier({
    required List<int> shaDigest,
  });

  void cgenObjectsCustomExtensionCustomExtensionSetCriticality({
    required CustomExtension that,
    required bool criticality,
  });

  SerialNumber cgenObjectsSerialNumberSerialNumberFromOwned({
    required List<int> bytes,
  });

  SerialNumber cgenObjectsSerialNumberSerialNumberFromU64({
    required BigInt num,
  });

  BigInt cgenObjectsSerialNumberSerialNumberLen({required SerialNumber that});

  Uint8List cgenObjectsSerialNumberSerialNumberToBytes({
    required SerialNumber that,
  });

  Future<CertificateBuilder> cgenCertificateCertificateBuilder();

  Future<Certificate> cgenCertificateCertificateDefault();

  Future<CertifiedKey> cgenCertificateCertificateGenerate({
    required Certificate that,
  });

  Certificate cgenCertificateCertificateNew();

  Future<Date> cgenObjectsDateDateDefault();

  Future<void> crateApiInitInitApp();

  Future<KeyIdMethod> cgenObjectsKeyIdMethodKeyIdMethodDefault();

  Future<SignatureAlgorithm>
  cgenObjectsSignatureAlgorithmSignatureAlgorithmDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertificateBuilder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertificateBuilder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CertificateBuilderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertificateErr;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertificateErr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CertificateErrPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertifiedKey;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertifiedKey;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CertifiedKeyPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CustomExtension;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CustomExtension;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CustomExtensionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SerialNumber;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SerialNumber;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SerialNumberPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String cgenObjectsCertifiedKeyCertifiedKeyCertPem({
    required CertifiedKey that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsCertifiedKeyCertifiedKeyCertPemConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsCertifiedKeyCertifiedKeyCertPemConstMeta =>
      const TaskConstMeta(
        debugName: "CertifiedKey_cert_pem",
        argNames: ["that"],
      );

  @override
  String cgenObjectsCertifiedKeyCertifiedKeySigningKeyPem({
    required CertifiedKey that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsCertifiedKeyCertifiedKeySigningKeyPemConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCertifiedKeyCertifiedKeySigningKeyPemConstMeta =>
      const TaskConstMeta(
        debugName: "CertifiedKey_signing_key_pem",
        argNames: ["that"],
      );

  @override
  void cgenObjectsCustomExtensionCustomExtensionContent({
    required CustomExtension that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsCustomExtensionCustomExtensionContentConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCustomExtensionCustomExtensionContentConstMeta =>
      const TaskConstMeta(
        debugName: "CustomExtension_content",
        argNames: ["that"],
      );

  @override
  bool cgenObjectsCustomExtensionCustomExtensionCriticality({
    required CustomExtension that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCgenObjectsCustomExtensionCustomExtensionCriticalityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCustomExtensionCustomExtensionCriticalityConstMeta =>
      const TaskConstMeta(
        debugName: "CustomExtension_criticality",
        argNames: ["that"],
      );

  @override
  CustomExtension cgenObjectsCustomExtensionCustomExtensionFromOidContent({
    required Uint64List oid,
    required List<int> content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_64_strict(oid, serializer);
          sse_encode_list_prim_u_8_loose(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension,
          decodeErrorData: null,
        ),
        constMeta:
            kCgenObjectsCustomExtensionCustomExtensionFromOidContentConstMeta,
        argValues: [oid, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCustomExtensionCustomExtensionFromOidContentConstMeta =>
      const TaskConstMeta(
        debugName: "CustomExtension_from_oid_content",
        argNames: ["oid", "content"],
      );

  @override
  CustomExtension? cgenObjectsCustomExtensionCustomExtensionNewAcmeIdentifier({
    required List<int> shaDigest,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(shaDigest, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension,
          decodeErrorData: null,
        ),
        constMeta:
            kCgenObjectsCustomExtensionCustomExtensionNewAcmeIdentifierConstMeta,
        argValues: [shaDigest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCustomExtensionCustomExtensionNewAcmeIdentifierConstMeta =>
      const TaskConstMeta(
        debugName: "CustomExtension_new_acme_identifier",
        argNames: ["shaDigest"],
      );

  @override
  void cgenObjectsCustomExtensionCustomExtensionSetCriticality({
    required CustomExtension that,
    required bool criticality,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
            that,
            serializer,
          );
          sse_encode_bool(criticality, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCgenObjectsCustomExtensionCustomExtensionSetCriticalityConstMeta,
        argValues: [that, criticality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsCustomExtensionCustomExtensionSetCriticalityConstMeta =>
      const TaskConstMeta(
        debugName: "CustomExtension_set_criticality",
        argNames: ["that", "criticality"],
      );

  @override
  SerialNumber cgenObjectsSerialNumberSerialNumberFromOwned({
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsSerialNumberSerialNumberFromOwnedConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsSerialNumberSerialNumberFromOwnedConstMeta =>
      const TaskConstMeta(
        debugName: "SerialNumber_from_owned",
        argNames: ["bytes"],
      );

  @override
  SerialNumber cgenObjectsSerialNumberSerialNumberFromU64({
    required BigInt num,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(num, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsSerialNumberSerialNumberFromU64ConstMeta,
        argValues: [num],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsSerialNumberSerialNumberFromU64ConstMeta =>
      const TaskConstMeta(
        debugName: "SerialNumber_from_u64",
        argNames: ["num"],
      );

  @override
  BigInt cgenObjectsSerialNumberSerialNumberLen({required SerialNumber that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsSerialNumberSerialNumberLenConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsSerialNumberSerialNumberLenConstMeta =>
      const TaskConstMeta(debugName: "SerialNumber_len", argNames: ["that"]);

  @override
  Uint8List cgenObjectsSerialNumberSerialNumberToBytes({
    required SerialNumber that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsSerialNumberSerialNumberToBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsSerialNumberSerialNumberToBytesConstMeta =>
      const TaskConstMeta(
        debugName: "SerialNumber_to_bytes",
        argNames: ["that"],
      );

  @override
  Future<CertificateBuilder> cgenCertificateCertificateBuilder() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder,
          decodeErrorData: null,
        ),
        constMeta: kCgenCertificateCertificateBuilderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenCertificateCertificateBuilderConstMeta =>
      const TaskConstMeta(debugName: "certificate_builder", argNames: []);

  @override
  Future<Certificate> cgenCertificateCertificateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_certificate,
          decodeErrorData: null,
        ),
        constMeta: kCgenCertificateCertificateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenCertificateCertificateDefaultConstMeta =>
      const TaskConstMeta(debugName: "certificate_default", argNames: []);

  @override
  Future<CertifiedKey> cgenCertificateCertificateGenerate({
    required Certificate that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_certificate(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr,
        ),
        constMeta: kCgenCertificateCertificateGenerateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenCertificateCertificateGenerateConstMeta =>
      const TaskConstMeta(
        debugName: "certificate_generate",
        argNames: ["that"],
      );

  @override
  Certificate cgenCertificateCertificateNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_certificate,
          decodeErrorData: null,
        ),
        constMeta: kCgenCertificateCertificateNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenCertificateCertificateNewConstMeta =>
      const TaskConstMeta(debugName: "certificate_new", argNames: []);

  @override
  Future<Date> cgenObjectsDateDateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_date,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsDateDateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsDateDateDefaultConstMeta =>
      const TaskConstMeta(debugName: "date_default", argNames: []);

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<KeyIdMethod> cgenObjectsKeyIdMethodKeyIdMethodDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_id_method,
          decodeErrorData: null,
        ),
        constMeta: kCgenObjectsKeyIdMethodKeyIdMethodDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCgenObjectsKeyIdMethodKeyIdMethodDefaultConstMeta =>
      const TaskConstMeta(debugName: "key_id_method_default", argNames: []);

  @override
  Future<SignatureAlgorithm>
  cgenObjectsSignatureAlgorithmSignatureAlgorithmDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signature_algorithm,
          decodeErrorData: null,
        ),
        constMeta:
            kCgenObjectsSignatureAlgorithmSignatureAlgorithmDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCgenObjectsSignatureAlgorithmSignatureAlgorithmDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "signature_algorithm_default",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertificateBuilder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertificateBuilder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertificateErr => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertificateErr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CertifiedKey => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CertifiedKey => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CustomExtension => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CustomExtension => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SerialNumber => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SerialNumber => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber;

  @protected
  CertificateBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertificateBuilderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertificateErr
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertificateErrImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertifiedKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CustomExtension
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SerialNumber
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SerialNumberImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CustomExtension
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertifiedKey
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CustomExtension
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SerialNumber
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SerialNumberImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertificateBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertificateBuilderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertificateErr
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertificateErrImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CertifiedKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CustomExtension
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SerialNumber
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SerialNumberImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CustomExtension
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
      raw,
    );
  }

  @protected
  SerialNumber
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
      raw,
    );
  }

  @protected
  Certificate dco_decode_box_autoadd_certificate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_certificate(raw);
  }

  @protected
  RsaKeySize dco_decode_box_autoadd_rsa_key_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rsa_key_size(raw);
  }

  @protected
  Certificate dco_decode_certificate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return Certificate.raw(
      ca: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      signature: dco_decode_signature_algorithm(arr[1]),
      notBefore: dco_decode_date(arr[2]),
      notAfter: dco_decode_date(arr[3]),
      subjectAltNames: dco_decode_list_String(arr[4]),
      serialNumber:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
            arr[5],
          ),
      distinguishedName: dco_decode_list_record_dn_type_string(arr[6]),
      keyUsages: dco_decode_list_key_usage_purpose(arr[7]),
      extendedKeyUsages: dco_decode_list_extended_key_usage_purpose(arr[8]),
      crlDistributionPoints: dco_decode_list_crl_distribution_point(arr[9]),
      customExtensions:
          dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
            arr[10],
          ),
      useAuthorityKeyIdentifierExtension: dco_decode_bool(arr[11]),
      keyIdentifierMethod: dco_decode_key_id_method(arr[12]),
      rsaKeySize: dco_decode_opt_box_autoadd_rsa_key_size(arr[13]),
    );
  }

  @protected
  CrlDistributionPoint dco_decode_crl_distribution_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return CrlDistributionPoint(uris: dco_decode_list_String(arr[0]));
  }

  @protected
  Date dco_decode_date(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Date(
      year: dco_decode_i_32(arr[0]),
      month: dco_decode_u_8(arr[1]),
      day: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  DnType dco_decode_dn_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DnType_CountryName();
      case 1:
        return DnType_LocalityName();
      case 2:
        return DnType_StateOrProvinceName();
      case 3:
        return DnType_OrganizationName();
      case 4:
        return DnType_OrganizationalUnitName();
      case 5:
        return DnType_CommonName();
      case 6:
        return DnType_CustomDnType(dco_decode_list_prim_u_64_strict(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ExtendedKeyUsagePurpose dco_decode_extended_key_usage_purpose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ExtendedKeyUsagePurpose_Any();
      case 1:
        return ExtendedKeyUsagePurpose_ServerAuth();
      case 2:
        return ExtendedKeyUsagePurpose_ClientAuth();
      case 3:
        return ExtendedKeyUsagePurpose_CodeSigning();
      case 4:
        return ExtendedKeyUsagePurpose_EmailProtection();
      case 5:
        return ExtendedKeyUsagePurpose_TimeStamping();
      case 6:
        return ExtendedKeyUsagePurpose_OcspSigning();
      case 7:
        return ExtendedKeyUsagePurpose_Other(
          dco_decode_list_prim_u_64_strict(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KeyIdMethod dco_decode_key_id_method(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return KeyIdMethod_Sha256();
      case 1:
        return KeyIdMethod_Sha384();
      case 2:
        return KeyIdMethod_Sha512();
      case 3:
        return KeyIdMethod_PreSpecified(
          dco_decode_list_prim_u_8_strict(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  KeyUsagePurpose dco_decode_key_usage_purpose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyUsagePurpose.values[raw as int];
  }

  @protected
  List<CustomExtension>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension,
        )
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CrlDistributionPoint> dco_decode_list_crl_distribution_point(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_crl_distribution_point)
        .toList();
  }

  @protected
  List<ExtendedKeyUsagePurpose> dco_decode_list_extended_key_usage_purpose(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_extended_key_usage_purpose)
        .toList();
  }

  @protected
  List<KeyUsagePurpose> dco_decode_list_key_usage_purpose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_usage_purpose).toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(DnType, String)> dco_decode_list_record_dn_type_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_dn_type_string)
        .toList();
  }

  @protected
  CustomExtension?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
            raw,
          );
  }

  @protected
  SerialNumber?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
            raw,
          );
  }

  @protected
  RsaKeySize? dco_decode_opt_box_autoadd_rsa_key_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rsa_key_size(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (DnType, String) dco_decode_record_dn_type_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_dn_type(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  RsaKeySize dco_decode_rsa_key_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsaKeySize.values[raw as int];
  }

  @protected
  SignatureAlgorithm dco_decode_signature_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SignatureAlgorithm.values[raw as int];
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CertificateBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertificateBuilderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertificateErr
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertificateErrImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertifiedKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CustomExtension
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SerialNumber
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SerialNumberImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CustomExtension
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertifiedKey
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CustomExtension
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SerialNumber
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SerialNumberImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertificateBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertificateBuilderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertificateErr
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertificateErrImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CertifiedKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CertifiedKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CustomExtension
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CustomExtensionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SerialNumber
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SerialNumberImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CustomExtension
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
      deserializer,
    ));
  }

  @protected
  SerialNumber
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
      deserializer,
    ));
  }

  @protected
  Certificate sse_decode_box_autoadd_certificate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_certificate(deserializer));
  }

  @protected
  RsaKeySize sse_decode_box_autoadd_rsa_key_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rsa_key_size(deserializer));
  }

  @protected
  Certificate sse_decode_certificate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ca = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_signature_algorithm(deserializer);
    var var_notBefore = sse_decode_date(deserializer);
    var var_notAfter = sse_decode_date(deserializer);
    var var_subjectAltNames = sse_decode_list_String(deserializer);
    var var_serialNumber =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
          deserializer,
        );
    var var_distinguishedName = sse_decode_list_record_dn_type_string(
      deserializer,
    );
    var var_keyUsages = sse_decode_list_key_usage_purpose(deserializer);
    var var_extendedKeyUsages = sse_decode_list_extended_key_usage_purpose(
      deserializer,
    );
    var var_crlDistributionPoints = sse_decode_list_crl_distribution_point(
      deserializer,
    );
    var var_customExtensions =
        sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
          deserializer,
        );
    var var_useAuthorityKeyIdentifierExtension = sse_decode_bool(deserializer);
    var var_keyIdentifierMethod = sse_decode_key_id_method(deserializer);
    var var_rsaKeySize = sse_decode_opt_box_autoadd_rsa_key_size(deserializer);
    return Certificate.raw(
      ca: var_ca,
      signature: var_signature,
      notBefore: var_notBefore,
      notAfter: var_notAfter,
      subjectAltNames: var_subjectAltNames,
      serialNumber: var_serialNumber,
      distinguishedName: var_distinguishedName,
      keyUsages: var_keyUsages,
      extendedKeyUsages: var_extendedKeyUsages,
      crlDistributionPoints: var_crlDistributionPoints,
      customExtensions: var_customExtensions,
      useAuthorityKeyIdentifierExtension:
          var_useAuthorityKeyIdentifierExtension,
      keyIdentifierMethod: var_keyIdentifierMethod,
      rsaKeySize: var_rsaKeySize,
    );
  }

  @protected
  CrlDistributionPoint sse_decode_crl_distribution_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uris = sse_decode_list_String(deserializer);
    return CrlDistributionPoint(uris: var_uris);
  }

  @protected
  Date sse_decode_date(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_i_32(deserializer);
    var var_month = sse_decode_u_8(deserializer);
    var var_day = sse_decode_u_8(deserializer);
    return Date(year: var_year, month: var_month, day: var_day);
  }

  @protected
  DnType sse_decode_dn_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return DnType_CountryName();
      case 1:
        return DnType_LocalityName();
      case 2:
        return DnType_StateOrProvinceName();
      case 3:
        return DnType_OrganizationName();
      case 4:
        return DnType_OrganizationalUnitName();
      case 5:
        return DnType_CommonName();
      case 6:
        var var_field0 = sse_decode_list_prim_u_64_strict(deserializer);
        return DnType_CustomDnType(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ExtendedKeyUsagePurpose sse_decode_extended_key_usage_purpose(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ExtendedKeyUsagePurpose_Any();
      case 1:
        return ExtendedKeyUsagePurpose_ServerAuth();
      case 2:
        return ExtendedKeyUsagePurpose_ClientAuth();
      case 3:
        return ExtendedKeyUsagePurpose_CodeSigning();
      case 4:
        return ExtendedKeyUsagePurpose_EmailProtection();
      case 5:
        return ExtendedKeyUsagePurpose_TimeStamping();
      case 6:
        return ExtendedKeyUsagePurpose_OcspSigning();
      case 7:
        var var_field0 = sse_decode_list_prim_u_64_strict(deserializer);
        return ExtendedKeyUsagePurpose_Other(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KeyIdMethod sse_decode_key_id_method(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return KeyIdMethod_Sha256();
      case 1:
        return KeyIdMethod_Sha384();
      case 2:
        return KeyIdMethod_Sha512();
      case 3:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return KeyIdMethod_PreSpecified(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  KeyUsagePurpose sse_decode_key_usage_purpose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return KeyUsagePurpose.values[inner];
  }

  @protected
  List<CustomExtension>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomExtension>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CrlDistributionPoint> sse_decode_list_crl_distribution_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CrlDistributionPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_crl_distribution_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExtendedKeyUsagePurpose> sse_decode_list_extended_key_usage_purpose(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExtendedKeyUsagePurpose>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_extended_key_usage_purpose(deserializer));
    }
    return ans_;
  }

  @protected
  List<KeyUsagePurpose> sse_decode_list_key_usage_purpose(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KeyUsagePurpose>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_usage_purpose(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(DnType, String)> sse_decode_list_record_dn_type_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(DnType, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_dn_type_string(deserializer));
    }
    return ans_;
  }

  @protected
  CustomExtension?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  SerialNumber?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  RsaKeySize? sse_decode_opt_box_autoadd_rsa_key_size(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rsa_key_size(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (DnType, String) sse_decode_record_dn_type_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_dn_type(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RsaKeySize sse_decode_rsa_key_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RsaKeySize.values[inner];
  }

  @protected
  SignatureAlgorithm sse_decode_signature_algorithm(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SignatureAlgorithm.values[inner];
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    CertificateBuilder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertificateBuilderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    CertificateErr self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertificateErrImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    CertifiedKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertifiedKeyImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CustomExtensionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SerialNumber self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SerialNumberImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CustomExtensionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    CertifiedKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertifiedKeyImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CustomExtensionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SerialNumber self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SerialNumberImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateBuilder(
    CertificateBuilder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertificateBuilderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificateErr(
    CertificateErr self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertificateErrImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertifiedKey(
    CertifiedKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CertifiedKeyImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CustomExtensionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SerialNumber self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SerialNumberImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
      self,
      serializer,
    );
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SerialNumber self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_certificate(
    Certificate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_certificate(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rsa_key_size(
    RsaKeySize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rsa_key_size(self, serializer);
  }

  @protected
  void sse_encode_certificate(Certificate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.ca, serializer);
    sse_encode_signature_algorithm(self.signature, serializer);
    sse_encode_date(self.notBefore, serializer);
    sse_encode_date(self.notAfter, serializer);
    sse_encode_list_String(self.subjectAltNames, serializer);
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
      self.serialNumber,
      serializer,
    );
    sse_encode_list_record_dn_type_string(self.distinguishedName, serializer);
    sse_encode_list_key_usage_purpose(self.keyUsages, serializer);
    sse_encode_list_extended_key_usage_purpose(
      self.extendedKeyUsages,
      serializer,
    );
    sse_encode_list_crl_distribution_point(
      self.crlDistributionPoints,
      serializer,
    );
    sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
      self.customExtensions,
      serializer,
    );
    sse_encode_bool(self.useAuthorityKeyIdentifierExtension, serializer);
    sse_encode_key_id_method(self.keyIdentifierMethod, serializer);
    sse_encode_opt_box_autoadd_rsa_key_size(self.rsaKeySize, serializer);
  }

  @protected
  void sse_encode_crl_distribution_point(
    CrlDistributionPoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.uris, serializer);
  }

  @protected
  void sse_encode_date(Date self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.year, serializer);
    sse_encode_u_8(self.month, serializer);
    sse_encode_u_8(self.day, serializer);
  }

  @protected
  void sse_encode_dn_type(DnType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DnType_CountryName():
        sse_encode_i_32(0, serializer);
      case DnType_LocalityName():
        sse_encode_i_32(1, serializer);
      case DnType_StateOrProvinceName():
        sse_encode_i_32(2, serializer);
      case DnType_OrganizationName():
        sse_encode_i_32(3, serializer);
      case DnType_OrganizationalUnitName():
        sse_encode_i_32(4, serializer);
      case DnType_CommonName():
        sse_encode_i_32(5, serializer);
      case DnType_CustomDnType(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_list_prim_u_64_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_extended_key_usage_purpose(
    ExtendedKeyUsagePurpose self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ExtendedKeyUsagePurpose_Any():
        sse_encode_i_32(0, serializer);
      case ExtendedKeyUsagePurpose_ServerAuth():
        sse_encode_i_32(1, serializer);
      case ExtendedKeyUsagePurpose_ClientAuth():
        sse_encode_i_32(2, serializer);
      case ExtendedKeyUsagePurpose_CodeSigning():
        sse_encode_i_32(3, serializer);
      case ExtendedKeyUsagePurpose_EmailProtection():
        sse_encode_i_32(4, serializer);
      case ExtendedKeyUsagePurpose_TimeStamping():
        sse_encode_i_32(5, serializer);
      case ExtendedKeyUsagePurpose_OcspSigning():
        sse_encode_i_32(6, serializer);
      case ExtendedKeyUsagePurpose_Other(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_list_prim_u_64_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_key_id_method(KeyIdMethod self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case KeyIdMethod_Sha256():
        sse_encode_i_32(0, serializer);
      case KeyIdMethod_Sha384():
        sse_encode_i_32(1, serializer);
      case KeyIdMethod_Sha512():
        sse_encode_i_32(2, serializer);
      case KeyIdMethod_PreSpecified(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_key_usage_purpose(
    KeyUsagePurpose self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    List<CustomExtension> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_crl_distribution_point(
    List<CrlDistributionPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_crl_distribution_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_extended_key_usage_purpose(
    List<ExtendedKeyUsagePurpose> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_extended_key_usage_purpose(item, serializer);
    }
  }

  @protected
  void sse_encode_list_key_usage_purpose(
    List<KeyUsagePurpose> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_usage_purpose(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_dn_type_string(
    List<(DnType, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_dn_type_string(item, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
    CustomExtension? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCustomExtension(
        self,
        serializer,
      );
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
    SerialNumber? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSerialNumber(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rsa_key_size(
    RsaKeySize? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rsa_key_size(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_dn_type_string(
    (DnType, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dn_type(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_rsa_key_size(RsaKeySize self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_signature_algorithm(
    SignatureAlgorithm self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CertificateBuilderImpl extends RustOpaque implements CertificateBuilder {
  // Not to be used by end users
  CertificateBuilderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CertificateBuilderImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CertificateBuilder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CertificateBuilder,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CertificateBuilderPtr,
  );
}

@sealed
class CertificateErrImpl extends RustOpaque implements CertificateErr {
  // Not to be used by end users
  CertificateErrImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CertificateErrImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CertificateErr,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CertificateErr,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CertificateErrPtr,
  );
}

@sealed
class CertifiedKeyImpl extends RustOpaque implements CertifiedKey {
  // Not to be used by end users
  CertifiedKeyImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CertifiedKeyImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CertifiedKey,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CertifiedKey,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CertifiedKeyPtr,
  );

  /// flutter_rust_bridge:sync
  String certPem() => RustLib.instance.api
      .cgenObjectsCertifiedKeyCertifiedKeyCertPem(that: this);

  /// flutter_rust_bridge:sync
  String signingKeyPem() => RustLib.instance.api
      .cgenObjectsCertifiedKeyCertifiedKeySigningKeyPem(that: this);
}

@sealed
class CustomExtensionImpl extends RustOpaque implements CustomExtension {
  // Not to be used by end users
  CustomExtensionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CustomExtensionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CustomExtension,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CustomExtension,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CustomExtensionPtr,
  );

  /// Obtains the content of the extension.
  /// flutter_rust_bridge:sync
  void content() => RustLib.instance.api
      .cgenObjectsCustomExtensionCustomExtensionContent(that: this);

  /// Obtains the criticality flag of the extension.
  /// flutter_rust_bridge:sync
  bool criticality() => RustLib.instance.api
      .cgenObjectsCustomExtensionCustomExtensionCriticality(that: this);

  /// Sets the criticality flag of the extension.
  /// flutter_rust_bridge:sync
  void setCriticality({required bool criticality}) => RustLib.instance.api
      .cgenObjectsCustomExtensionCustomExtensionSetCriticality(
        that: this,
        criticality: criticality,
      );
}

@sealed
class SerialNumberImpl extends RustOpaque implements SerialNumber {
  // Not to be used by end users
  SerialNumberImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SerialNumberImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SerialNumber,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SerialNumber,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SerialNumberPtr,
  );

  /// Return the length of the serial number in bytes.
  /// flutter_rust_bridge:sync
  BigInt len() =>
      RustLib.instance.api.cgenObjectsSerialNumberSerialNumberLen(that: this);

  /// Return the byte representation of the serial number.
  /// flutter_rust_bridge:sync
  Uint8List toBytes() => RustLib.instance.api
      .cgenObjectsSerialNumberSerialNumberToBytes(that: this);
}
